import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Hero from "./components/Hero";
import About from "./components/About";
import Product from "./components/Product";
import StatsSection from "./components/StatsSection";
import StrengthSection from "./components/StrengthSection";
import TestimonialSection from "./components/TestimonialSection";
import ImageCards from "./components/ImageCards";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DECENT SHUTTERING SOLUTIONS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <Hero/>
        <About/>
        <Product/>
        <StatsSection/>
        <StrengthSection/>
        <TestimonialSection/>
        <ImageCards/>
        <Footer/>
      </body>
    </html>
  );
}
